export const CLUSTER_ORDER = [
    'PLEXBSB', 'PLEXBS2', 'PLEXBS3', 'PLEXHOM', 'PLEXDES', 'PLEXLAB', 'PLEXBAS', 'PLEXLUX',
    'SSIPR1', 'SSIPR2', 'SSIPR3', 'SSIHOM', 'SSIDES', 'SSILAB',
    'KVMPRD', 'KVMHOM', 'KVMDES', 'KVMLAB'
];
